# Finetuning configuration
seed: 0
pretrained: True
prompt_length: 'fixed'  # 'fixed' or 'variable'
n_alphabets: 26        # Total number of tokens "a-z" + " "
seq_len: 6              # Length of tokens in data prompt
n_functions: 6  # Number of maximum functions per composition
model_name: "gemma1"
function_type: "uniform"
device : "cuda"
bf16: True
epochs: 5
data_path: "/scratch4/workspace/ppruthi_umass_edu-CG/task_based_compositional_generalization/data/diverse/fixed/nalph_26_seqlen_6_fnlen_6_taskmaxlen_6/step_by_step/coverage_6_5_0"
output_dir: "/scratch4/workspace/ppruthi_umass_edu-CG/task_based_compositional_generalization/models/ckpts/diverse/fixed/nalph_26_seqlen_6_fnlen_6_taskmaxlen_6/step_by_step/coverage_6_5_0/gemma1"
prompt_mode: "step_by_step"
train_split: "coverage_6_5_0"
task_max_length: 6
num_workers: 4
batch_size: 1

net:
  compile: False
  prompt_length: "fixed"
  pos_embedding_type: "abs"

optimizer:
  learning_rate: 0.00002
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: True
  warmup_iters: 500
  min_lr: 0.000006

log: 
  eval_interval: 500
  log_interval: 100
